<?php 
include('header_new.php');
//include_once("db_connect.php");
?>
<title>BMTC</title>
<script type="text/javascript" src="script/validation.min.js"></script>
<script type="text/javascript" src="script/register.js"></script>
<link href="css_fe/style.css" rel="stylesheet" type="text/css" media="screen">
<?php include('container.php');?>

<div class="container">
	
	
	<div class="register_container">
	<h3 class="form-signin-heading" align="center">Subscriber Terms - BookMyTestCenter</h3><hr />
	<div id="error">
	</div>
    
    
    
     <div class="form-group col-12 col-lg-12">
    <label style="font-size:15px; color:#333">



<p>Terms of Use for the use of BookMyTestCenter ("Application") and the other Services provided by Testpan India Private Limited ("Testpan").</p>

<p>Testpan India Private Limited ("us", "we", or "Testpan", which also includes its affiliates  is the author and publisher of the mobile application "BookMyTestCenter" ("Application")   as well as software and applications provided by Testpan, including but not limited to the mobile application. </p>

<p>These Terms of Use constitute the agreement (the "Agreement" or "Terms of Use") among Testpan and the client of Testpan's   Services ("User", as defined in Section 2 of this agreement). Your utilization of Testpan's   Services, which incorporate Application and different subordinate Services available on the Application and for which a no   sum is payable for use (hereinafter individually referred to as the " Service" and collectively referred to as the "  Services") is subject to the following terms and conditions. However, the Testpan may in the future might charge for the   services, and if any change of policy regarding   services takes place the Testpan will notify its users accordingly.</p>

<p>This Agreement is an electronic record as far as Information Technology Act, 2000 and generated by a computer framework and doesn't require any physical or computerized marks. This Agreement is distributed as per accordance of Rule 3 (1) of the Information Technology (Intermediaries rules) Rules, 2011 that require publishing the principles and guidelines, privacy policy and Terms of Use for access or use of the   Services.</p>

<p>This Agreement provides the terms and conditions for the usage of   services, primarily an android application hosted and managed remotely through the mobile application as described in section 3.9 of this agreement. The Application is owned and operated by Testpan India Private Limited.</p>




<p><strong>1. YOUR AGREEMENT WITH TESTPAN</strong></p>

<p>1.1	We reserve the right to modify the Terms of Use at any time without giving you any prior notice. Your utilization of the Services following any such alteration comprises your consent to follow and be bound by the terms of use as modified. Any additional terms and conditions, disclaimers, privacy policies and other policies applicable to general and specific areas of these Services or to specific   Services are also considered as Terms of Use. By agreeing to these terms, you also agree to the terms of utilization of the Service, which are accessible at the Application.</p>

<p>1.2	You acknowledge that you will be bound by this Agreement for availing any of the   Services offered by us.</p>

<p>1.3 Your access to use the   Services will be solely at the discretion of Testpan.</p>

<p><strong>2. WHO IS TESTPAN?</strong></p>

<p>Testpan is the author and publisher of the mobile application BookMyTestCenter and all their variants, editions, addons and additional   services or services (including all files and images contained in or generated by the software, and accompanying data, together the "Software"). The Services have been designed for use  by Private Test Centers/Labs, Engineering Colleges, Business Schools, Schools, ITI, University (collectively referred as "Institutions") engaged in conducting computer based online examination. Testpan also has a network of Online Test Terminals across India, which are used to deliver online tests. </p>
<p>Testpan makes no express or implied representations about the   services. Testpan does not authorise anyone to make a warranty on Testpan's behalf and you may not rely on any statement of warranty as a warranty by Testpan. All users of the Services are together termed as ("Users"or "you" or "your").</p>

 <p><strong>3. TERMS OF USE</strong></p>

<p>3.1 By utilizing the Services, you agree that you have read and understood these Terms of Use and you consent to be bound by these Terms of Use and utilize these   Services in consistence with these Terms of Use. PLEASE READ THESE TERMS OF USE CAREFULLY. IN THE EVENT THAT YOU DO NOT AGREE TO BE BOUND BY (OR CANNOT COMPLY WITH) ANY OF THE TERMS BELOW, DO NOT CLICK/SIGN THE "I AGREE" BOX, DO NOT COMPLETE THE REGISTRATION PROCESS, AND DO NOT ATTEMPT TO USE THE SERVICE. You explicitly represent and warrant that you won't utilize these   Services in the event that you do not understand, consent to become a party to, and abide by all of the terms and conditions specified below. Any violation of these Terms of Use may result in legal liability upon you. Nothing in these Terms of Use should be construed to confer any rights to any third party or any other person. YOUR USE OF THE APPLICATION MEANS YOU ARE CONSENTING TO THIS AGREEMENT.</p>

<p>3.2 The Agreement is published in compliance of, and is governed by the provisions of Indian law, including but limited to:</p>

<p>3.2.1 The Indian Contract Act, 1872,</p>

<p>3.2.2 The (Indian) Information Technology Act, 2000, and</p>

<p>3.2.3 The rules, regulations, guidelines and clarifications framed thereunder, including the (Indian) Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Information) Rules, 2011 (the "SPI Rules"), and the (Indian) Information Technology (Intermediaries Guidelines) Rules, 2011 (the "IG Rules").</p>

<p>3.3 Testpan provides a condition to users for the use and access to the   Services that is User's acceptance of this Agreement. If a user does not agree with any provision of the same, such user is required to leave this computer resource/ the services immediately and immediately discontinue use of all   Services available at the Testpan.</p>

<p>3.4 Testpan authorises the User to view and access the content available on the   Services solely for booking, delivering and communicating only as per this Agreement. The contents of the   Services, information, text, graphics, images, logos, button icons, software code, design, and the collection, arrangement and assembly of content on the Services (collectively, "Testpan Content"), are the property of Testpan and are protected under copyright, trademark and other laws. User is not permitted to modify the Testpan Content or reproduce, display, publicly perform, distribute, or otherwise use the Testpan Content in any way for any public or commercial purpose or for personal gain.</p>

<p>3.5 Multiple Users are not permitted to share the same/single login. </p>

<p>3.6 If you are a student, associate, consultant, intern or are in any way associated with the Institutions that has subscribed to the Services and the subscribing Institution has authorised you, explicitly or implicitly, to use the Services, this Agreement is a three way agreement between you, the Institution and Testpan. Both the Institute and Testpan may seek recourse against you for any violation of the terms of this Agreement.</p>

<p>3.7 Users may not transfer (including by way of sublicense, lease, assignment or other transfer, including by operation of law) their login or right to utilize the   Services to any third party. You, the User, are exclusively responsible for the manner in which anyone you have authorised to utilize the Services and for ensuring that all of such Users comply with all of the terms and conditions of this Agreement. Any violation of the terms and/or conditions of this Agreement by any such User shall be deemed to be a violation thereof by you.</p>

<p>3.8 These Terms of Use will also be applicable to Users who access Application features using native mobile applications published by Testpan including but not limited to its applications for devices running on platforms such as iOS, Android, Windows, and any derivatives or any other platforms. Additional terms of use may be applicable to Users while accessing Software using such mobile applications.</p>

<p>3.9 You agree that any registration information you give to Testpan will always be true, accurate, correct, complete and up to date, to our knowledge. Any phone number used to register with the Services be registered in your name and you might be asked to provide supporting documents to prove the same.</p>

<p>3.10 You agree that you will not use the Services provided by Testpan for any unauthorised and unlawful purpose. </p>

<p>3.11 You agree to use the   Services only for purposes that are permitted by (a) the Terms of Use and (b) any applicable law, regulation and generally accepted practices or guidelines in the relevant jurisdictions (including any laws regarding the export of data or software to and from India or other relevant countries).</p>

<p>3.12 You agree not to access (or attempt to access) any of the Services by any means other than through the interface that is provided by Testpan, unless you have been specifically allowed to do so in a separate agreement with Testpan.</p>

<p>3.13 You agree that you will not engage in any activity that interferes with or disrupts the   Services (or the servers and networks which are connected to the Services).</p>

<p>3.14 You agree that you will not reproduce, duplicate, copy, transfer, license, rent, sell, trade or resell the Software or any other Services for any purpose whatsoever.</p>

<p>3.15 You agree that you are solely responsible for (and that Testpan has no responsibility to you or to any third party for) any breach of your obligations under the Terms of Use and for the consequences (including any loss or damage which Testpan may suffer) of any such breach.</p>

<p>3.16 You shall indemnify Testpan for any claims, losses or damages, or for the costs of any regulatory or court proceedings suffered by Testpan as a result of your breach under any applicable law.</p>

<p>3.17 You expressly acknowledge and agree that your use of the Services is at your sole risk and that the   Services are provided "as is" and "as available".</p>

<p>3.18 You agree that you will not make any unsolicited calls or use any information displayed on the Testpan, an online platform; to breach any applicable rules and guidelines related to unsolicited commercial communications, including but not limited to regulations & guidelines such as TRAI guidelines for telemarketers, or otherwise violate applicable law while using the Services.</p>

<p>3.19 You agree that this Agreement and the Services of Testpan are subject to any modification, or may be removed by Testpan, as a result of change in government regulations, policies and local laws as applicable.</p>

<p>3.20 You agree and understand that you are responsible for maintaining the confidentiality of passwords associated with any login you use to access the Application.</p>

<p>3.21 Your use of each Service confers upon you only the rights and obligations relating to such   Service, and not to any other Service or service that may be provided by Testpan. For instance, being a subscriber to BookMyTestCenter does not automatically entitle you to a higher ranking on Testpan's Institution search facility.</p>

<p><strong>4. Use of   Services</strong></p>

<p>4.1 Testpan provides Application through Google Play (Android) & App Store (iOS). Testpan is not responsible for and does not deal with any consumer managed by User through the native mobile applications and only provides access of the Application to User through Google Play (Android) & App Store (iOS). </p>

<p>       Testpan does not transfer either the title or the intellectual property rights to the Application and other its   Services, and Testpan (or its licensors) retain full and complete title to the Application as well as all intellectual property rights therein. User agrees to use the Services and the materials provided therein only for purposes that are permitted by: (a) this Agreement; and (b) any applicable law, regulation or generally accepted practices or guidelines in the relevant jurisdictions. Information provided by a User to Testpan may be used, stored or republished by Testpan or its affiliates even after the termination of these Terms of Service.</p>

<p>4.2 Testpan offers its Services on as is basis and has the sole right to modify any feature or customise them at its discretion and there shall be no obligation to honour customisation requests of any User. </p>

<p>4.3 User shall not access the Services of Testpan if the User or the organisation that he/she/it represents is Testpan's direct competitor, except with Testpan's prior written consent. In addition, the User shall not access the   Services for purposes of monitoring their availability, performance or functionality, or for any other benchmarking or competitive purposes.</p>

<p>4.4 Testpan provides, at its discretion basic support for the Services at no additional charge, and/or upgraded support if purchased separately and will use commercially reasonable efforts to make the   Services available 24 hours a day, 7 days a week, except for (i) planned downtime (of which Testpan shall give at least 8 hours' notice to Users via the   Services and which Testpan shall schedule to the extent practicable during the weekend hours from 6:00 p.m. Indian Standard Time (IST) Friday to 6:00 a.m. Indian Standard Time (IST) Monday), or (ii) any unavailability caused by circumstances beyond Testpan's reasonable control, including without limitation, acts of God, acts of government, flood, fire, earthquakes, civil unrest, acts of terror, strikes or other labour problems, or internet service provider failures or delays. Testpan will provide the   Services only in accordance with applicable laws and government regulations.</p>

<p>4.5 Notwithstanding anything to the contrary contained herein, Testpan does not warrant that its   Services will always function without disruptions, delay or errors. A number of factors may impact the use of the   Services (depending on the   Services used) and native mobile applications and may result in the failure of your communications including but not limited to: your local network, firewall, your internet service provider, the public internet, your power supply and telephony services. Testpan takes no responsibility for any disruption, interruption or delay caused by any failure or inadequacy in any of these items or any other items over which we have no control.</p>

<p>4.6 In the event the Services are not available due to apparent default at Testpan's end or are rendered unusable, Testpan may at its discretion extend the Service period of the Institution only by such number of calendar days when the   Services were not available. However, you shall agree that Testpan is not responsible and will not be held liable for any failure of intermediary services such as internet connectivity failure or telephonic disconnections.</p>

<p>4.7 The   Services may be subject to certain limitations, such as limits on disk storage space, on the number of calls Users are permitted to make against Testpan's application programming interface, and other limitations dependent on the 'User Plan', for example, number of SMS, number of bookings, number of users or accounts, validity of Services and any other limitations. Any such limitations are specified in the User Plans. The   Services have been designed to provide real time information to enable User to monitor such User's compliance with such limitations.</p>

<p>4.8 Notwithstanding anything to the contrary contained herein, Institution alone shall be liable for Institution's dealings and interaction with consumer, his/her representatives or affiliates, searching for Institution through the Application (the "EndUser") contacted or managed through the Application and Testpan shall have no liability or responsibility in this regard. Testpan does not guarantee or make any representation with respect to the correctness, completeness or accuracy of the information or detail provided by End-Users or any third party through the   Services. </p>

<p>4.9 Testpan may, at its sole discretion, suspend User's ability to use or access the   Services at any time while Testpan investigates complaints or alleged violations of this Agreement, or for any other reason.</p>

<p>4.10 Testpan reserves the right to use all information captured in its   Services in anonymous form for the purpose of its   Services improvements, and providing analytics and business intelligence to third parties. On the basis of such information, Testpan tries to make its   Services more useful in following way:</p>
<li>User will get preloaded test center data where mentioned your registered number in test center database.</li>
<li>User can change/edit demography of your preloaded test center & upload photographs with geo-tag (Current Address + Current Date + Current Time).</li>
<li>User can add new test center & upload photographs with geo-tag (Current Address + Current Date + Current Time).</li>
<li>If user will change or update data of preloaded or new test center (new test center initially user was added through app), TESTPAN team will start the verification process and user can view status in my center page (Submitted/Verification in progress/Approved).  </li>
<li>Manage here your project of other client with our app & we will notify to user according to availability of dates and seats of test center.</li>
<li>Book here your test center through app of TESTPAN upcoming projects.</li>
<li>User can view projects updation (Seats, batches and exam dates), which was booked by TESTPAN only. </li>
<li>User can give feedback in contact US page.</li>
<li>Users can use the rectification tools provided by Testpan or contact Testpan immediately for rectifications. Testpan shall bear no liability or responsibility in this regard.</li>

<p>4.11 Testpan reserves the right to use the following types of information stored in our Application / software:</p>
<li>Institution information</li>
<li>End-Users demographic information as anonymised form</li>
<li>End-Users information in relation to the exam (anonymised form).</li>

<p>4.12 Testpan automatically starts the verification process if the user opts for the change of Institution and accordingly notifies the user regarding the available seats and dates of Institution. Testpan on its own, does not list any Personally Sensitive Information of such Institutions and users. Testpan reserves the right to list Institutions who are not a party to this Agreement and the Institutions who have subscribed to this Terms of Use are listed along with them. Thereon, Testpan reserves the right to modify the listing of Institutions on its Applications.</p> 


<p>4.13 The Services available by Testpan accepts online booking requests for all Institution listed and displayed on its Application. Testpan intends to take all reasonable steps to duly inform the test centers via phone and email for booking requests made on thorugh Application. However, it is possible that some booking requests do not reach the center in a timely manner due to technical or operational reasons including but not limited to cases when test center do not respond to phone calls made by Testpan or when test centers do not read email or text messages sent by Testpan in timely manner. Testpan shall have no liabilty or responsibility in this regard.</p>
      

<p>4.14 While Testpan makes every possible effort to ensure a confirmed booking for an EndUser who requested a booking on the Service, Testpan does not guarantee that bookings will be confirmed in all cases. Further, Testpan has no liability if such booking is confirmed but later cancelled by any of the End-Users, or the Institution is not available as per the given time.</p>

<p>4.15 Certain   Services (including ancillary Services) may be subject to additional limitations, restrictions, terms and/or conditions specific to such Software ("Specific Terms"). In such cases, the applicable Specific Terms will be and your access to and use of the relevant Services will be contingent upon your acceptance of and compliance with such Specific Terms.</p>

<p>4.16 Testpan reserves the right to add new functionality, remove existing functionality, and modify existing functionality to its Services as and when it deems fit, and make any such changes available in newer versions of its Services or native mobile application or all of these at its discretion. All Users of its   Services will be duly notified upon release of such newer versions and Testpan reserves the right to automatically upgrade all Users to the latest version of its Software as and when it deems fit.</p>

<p>4.17 BookMyTestCenter Terms of Use:</p>

<p>4.17.1The Institution agrees that if the Application is being used by its employees or agents, including receptionists, such employees or agents will use the Application in accordance with this Agreement.</p>

<p>4.17.2User can use BookMyTestCenter to book Test Center with End-Users, send End-Users reminders for booking, and record their data.</p>

<p>4.17.3BookMyTestCenter being an ancillary product of Testpan, the reviews and recommendations shared over BookMyTestCenter can be also displayed on the Application. Reviews and recommendations of the End-Users not registered with Testpan may be displayed on the Application through BookMyTestCenter. User agrees that Testpan shall not be responsible for any of the reviews made on the Application.</p>

<p>4.17.4 Testpan reserves the right to make any further operational changes to the Application, at its discretion and the Institutions will be notified of such changes or updates with a prior notice. The extension or withdrawal of such facility shall be intimated to you by Testpan.</p>

<p>4.17.5 User shall agree that they will be subscribing to the Application for the purpose of EndUser management and will not use the   Services provided by Testpan for any unauthorized and unlawful purpose. You will not impersonate another person.</p>

<p>4.17.6 User shall agree that you will indemnify and keep indemnified Testpan for all costs, damages and losses in case of any breach of security procedures by the User(s), User's employees or its vendors.</p>

<p>4.17.7 Any communication sent by or through Testpan to the clients or customers (whether or not End-Users) of a particular Institution is based solely on information uploaded by such Institute on the BookMyTestCenter software. The accuracy and completeness of such information (including but not limited to contact details of the client or customer) is the sole responsibility of the Institute. Testpan will not be responsible for the incompleteness or inaccuracy such information, including if as a result of such inaccuracy, a communication is sent to an unintended recipient.</p>

<p>4.17.8 Testpan may add new Services for additional fees and charges for existing   Services, at any time in its sole discretion. Fees if at any point of time made applicable  for the   Services being provided, may be amended  at Testpan's sole discretion from time to time, shall apply. The   fees if applicable at any stage, may be non-refundable.</p>

<p>4.17.9 You agree that the billing credentials provided by you for any booking from Testpan will be accurate and you shall not use billing credentials that are not lawfully owned by you.</p>

<p>4.17.10 Testpan in future may make available an offline fee payment facility, supported by a third party vendor. Testpan is not responsible for any loss or damage caused to the User using this payment facility provided by such third party vendor.</p>

<p>4.19 Testpan reserves the right to modify the fee structure by providing a 30 (thirty) days' prior notice, either by notice on the   Services or through email to the authorized User, which shall be considered as valid and agreed communication. Upon the User not communicating any response to Testpan to such notice, Testpan shall apply the modified fee structure effective from the expiry of the said notice period. This clause would be applicable after Testpan imposes fee structure for its services.</p>

<p>4.20 In order to process the fee payments, Testpan might require details of User's bank account, credit card number and other such financial information. Users are directed to check our privacy policy on how Testpan uses the confidential information provided by Users.</p>

<p>4.21 Notwithstanding anything to the contrary contained herein, in case the payments are made by a User through credit card, an invoice for subsequent period/renewals shall be generated 10 (ten) days prior to the expiry of the existing   period and an email will be sent to such User registered with Testpan intimating such User about expiration of the current service period and that the credit card of such User registered with Testpan  will be charged automatically against payment of service fee for subsequent   period, along with a copy of the invoice for the subsequent   period/renewal. Subject to the provisions of section 8.2 below, if a User is not willing to continue or renew the period of Services, the same shall be communicated to Testpan of such intimation to discontinue the services, Testpan shall be entitled to charge the credit card of the User registered with Testpan on the day the current   period expires. This clause would be applicable after Testpan imposes fee structure for its services.</p>


<p>4.22 Testpan shall send an intimation of receipt of fee (if applicable) from the Users through an email within 7 (seven) working days of receipt of fee into Testpan's designated bank account.</p>

<p>4.23 In case of nonpayment of any fee beyond the date a payment becomes overdue (overdue date), Testpan reserves the right to take any or all of the following actions as it deems appropriate (i)reduce all   Service credits in Users' Services account to 0 (zero) anytime after 7 (seven) days from the overdue date, including but not limited to SMS and Call credits. (ii)discontinue the   Services to the User any time after 30 (thirty) days from the overdue date. (iii) delete all information in User's account any time after 90 (ninety) days from the overdue date. This clause would be applicable after Testpan imposes fee structure for its services.</p>


<p>4.24 Fees and charges shall be calculated solely based on records maintained by Testpan or its third party billing provider. No other information of any kind shall be acceptable by us or have any effect under this agreement. Decision of Testpan shall be final and binding in relation to any fees payable by Users. This clause would be applicable after Testpan imposes fee structure for its services.</p>


<p>4.25 You can cancel your access to the Services by contacting our customer support by email at admin@testpanindia.com. The one time setup fees shall not be refunded to the User.</p>

<p>4.26 Testpan will not be liable to you or to any third party for any modification, suspension, or discontinuance of the   Services, or parts thereof, except that you are only entitled to a prorated refund representing the unused (as of the date of termination) portion of any fees (if applicable), paid deposits or payments for   Services other than the nonrefundable one time setup fees as due prior to permanent discontinuation the   Services or upon the expiry of 45 (forty five) days from the date of your written notice to Testpan. Testpan shall have the right to deduct any taxes that are due in relation to the refund amount (if any). The   fees are non transferables and the payment made by the User for a particular   Service cannot be transferred or carried over to another Service.</p>


<p><strong>5. Collection, Use, Storage and Transfer of Personal Information</strong></p>

<p>5.1 The terms "personal information" and "sensitive personal data or information" are defined under the SPI Rules, and are reproduced in the privacy policy ("Privacy Policy") available in this Application.</p>

<p><strong>6. Covenants</strong></p>

<p>6.1 As mandated by Regulation 3(2) of the IG Rules, Testpan hereby informs the User that the User is not permitted to host, display, upload, modify, publish, transmit, update or share any information that:</p>
<li>Belongs to another person and to which the User does not have any right to</li>
<li>Is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever</li>
<li>Harm minors in any way</li>
<li>Infringes any patent, trademark, copyright or other proprietary rights</li>
<li>Violates any law for the time being in force</li>
<li>Deceives or misleads the addressee (or EndUser or User) about the origin of such messages or communicates any information which is grossly offensive or menacing in nature</li>
<li>Impersonate another person</li>
<li>Contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource</li>
<li>Threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting any other nation.</li>

<p>6.2 The User is also prohibited from:</p>
<li>Violating or attempting to violate the integrity or security of the   Services or any Testpan Application / Software</li>
<li>Transmitting any information (including job posts, messages and hyperlinks) on or through the   Services that is disruptive or competitive to the provision of   Services byTestpan</li>
<li>Intentionally submitting on the Services any incomplete, false or inaccurate information</li>
<li>Making any unsolicited communications to other Users</li>
<li>Using any engine, software, tools, agent or other device or mechanism (such as spiders, robots, avatars or intelligent agents) to navigate or search the Service</li>
<li>Attempting to decipher, decompile, disassemble or reverse engineer any part of the   Services unless explicitly permitted by Testpan</li>
<li>Copying or duplicating in any manner any of the Testpan content or other information available from the Service</li>
<li>Framing or hotlinking or deep linking any Testpan content</li>
<li>Circumventing or disabling any digital rights management, usage rules, or other security features of the Software</li>

<p>6.3 Testpan, upon obtaining knowledge by itself or being brought to actual knowledge by an affected person in writing or through email signed with electronic signature about any such information as mentioned in Section 6.2 above, shall be entitled to disable such information that is in contravention of Section 6.2. Testpan shall be entitled to preserve such information and associated records for at least 90 (ninety) days for service on to governmental or investigative authorities for investigation purposes.</p>

<p>6.4 In case of noncompliance with any applicable laws, rules or regulations, or the Agreement (including the privacy policy) by a User, Testpan has the right to immediately terminate the access or usage rights of the User to the   Services and to remove non-compliant information.</p>

<p>6.5 Testpan may disclose or transfer User Information (as defined in the privacy policy) to its affiliates, and you hereby consent to such transfer. The SPI Rules only permit Testpan to transfer sensitive personal data or information including any information, to any other body corporate or a person in India, or located in any other country, that ensures the same level of data protection that is adhered to by Testpan as provided for under the SPI Rules, only if such transfer is necessary for the performance of the lawful contract between Testpan or any person on its behalf and the user or where the User has consented to data transfer.</p>

<p>6.6 Testpan respects the intellectual property rights of others and we do not hold any responsibility for any violations of any intellectual property rights.</p>

<p><strong>7. Liability</strong></p>

<p>7.1 Testpan shall not be responsible or liable in any manner to the Users for any losses, damages, injuries or costs incurred by the Users as a result of any disclosures made by Testpan, where the User has consented to the making of disclosures by Testpan. If the User had denied such consent under the terms of the privacy policy, then Testpan shall not be responsible or liable in any manner to the User for any losses, damages, injuries or expenses incurred by the User as a result of any disclosures made by Testpan prior to its actual receipt of such revocation.</p>

<p>7.2 The User shall not hold Testpan responsible or liable in any way for any disclosures by Testpan under Regulation 6 of the SPI Rules.</p>

<p>7.3 Testpan shall not be liable for ways in which EndUser data is used by Institutions, and other authorized users of Software at a Practice. It is the responsibility of the Test Center alone to ensure that the EndUser data either stored in Software or taken out from Software by printing or exporting to PDF, CSV or any other computer file format or data stored offline in mobile devices of users accessing Software through mobile applications published by Testpan, is used in compliance to local privacy laws applicable.</p>
 
<p>7.4 The   Services of Testpan may be linked to the services of third parties, affiliates and business partners. Testpan has no control over, and not liable or responsible for content, accuracy, validity, reliability, quality of such   Services or made available by/through our Services. Inclusion of any link on the   Services does not imply that Testpan endorses the linked site. User may use the links and these   Services at User's own risk.</p>

<p>7.5 Testpan shall not be liable for any damages to, or viruses that may infect User's equipment on account of User's access to, use of, or browsing the Services or the downloading of any material, data, text, images, from the Service. If a User is dissatisfied with the Service, User's sole remedy is to discontinue using the Testpan's   Services.</p>

<p>7.6 The Services may enable User to communicate with other Users or to post information to be accessed by others, whereupon other Users may collect such data. Such Users, including any moderators or administrators, are not authorized Testpan representatives or agents, and their opinions or statements do not necessarily reflect those of Testpan, and they are not authorized to bind Testpan to any contract. Testpan hereby expressly disclaims any liability for any reliance or misuse of such information that is made available by Users or visitors in such a manner.</p>

<p>7.7 Testpan or any of its directors, officers, employees, agents or content or service providers (collectively, the "protected entities") shall not be liable for any direct, indirect, special, incidental, consequential, exemplary or punitive damages arising from, or directly or indirectly related to the use of   services or the content, materials and functions related thereto, User's provision of information via the   Services of the Testpan, lost business or lost sales, even if such protected entity has been advised of the possibility of such damages.  In no event shall the total aggregate liability of the protected entities to the user for damages or losses or cause of action exceed the amount paid by user to protected entities.</p>

<p>7.8 In no event shall the protected entities be liable for failure on the part of the Users to provide agreed   Services. In no event shall the protected entities be liable for any comments or feedback given by any of the Users in relation to the   Services provided by a User.</p>

<p>7.9 The listing order of Institutions on the Services is based on numerous factors including End-Users' comments and feedback. In no event shall the protected entities and the Testpan be liable or responsible for the listing order of Institutions on the Service. Further, Testpan shall not be responsible for adverse feedback or comments, or ratings on the   Services which are a subject matter of automated processes, and Testpan disclaims any liability for lost business or reputation of a User due to information, data or ratings that are available on the Service. Testpan at its discretion hold the sole right to display the listing order of the Institutions.</p>

<p>7.10 The reviews and the feedbacks are displayed by the Testpan at its discretion. You agree that Testpan may contact you through telephone, email, sms, social media platforms or at your contact details for the limited purpose of:</p>
     <p> Obtaining feedback in relation to Testpan's Services and/or</p>
    <p>  Obtaining feedback in relation to any Institution. </p>

<p><strong>8. Indemnity</strong></p>

<p>User consent to indemnify and hold innocuous, without opposition, Testpan, its officials, executives, workers and operators from and against any claims, activities as well as requests as well as liabilities or potentially misfortunes or potentially harms emerging from or resulting from their utilization of  and use of the Application  or their breach of the terms.</p>

<p><strong>9. Spamming</strong></p>

<p>Testpan has a zero tolerance spam policy. Testpan employs controls on user permission to receive Content from Testpan's Services and has easily accessible ways for users to block or not receive content if they chose to. However, Testpan's policy on spam is clearly stated below:
Spamming is defined as the practice of (i) sending unsolicited messages, likely with commercial content, (ii) in large quantities (iii) to an indiscriminate set of recipients. The result of this practice is termed "Spam".</p>
<p>The sender of any message deemed to be "spam" is liable for Rs. 5,000/ for each EndUser that receives each unauthorized message. The sender of 'Spam' will pay all fees owed to Testpan within thirty (30) days of such transmission.</p>

<p><strong>10. Term, Termination and Disputes</strong></p>

<p>10.1 Testpan reserves the right to suspend or terminate a User's access to the Application and the Services with or without notice and to exercise any other remedy available under law, in cases where such user breaches any terms and conditions of the agreement; an outsider reports infringement of any of its privilege because of your utilization of the Administrations; Testpan is unable to verify or authenticate any information provided to Testpan by a user; Testpan has reasonable grounds for suspecting any illicit, false or abusive activity on the part of such user; or Testpan believes in its sole prudence that user's activity may cause lawful obligation for such user, other users or for Testpan or are contrary to the interest of the site.</p>

<p>10.2 Once temporarily suspended, indefinitely suspended or terminated, the User may not continue to use the Application under the same account, a different account or re-register under a new account. On termination of an account due to the reasons mentioned herein, such User shall no longer have access to data, messages, files and other material kept on the Application by such User. The User shall ensure that he/she/it has continuous backup of his/her data the User has rendered in order to comply with the User's record keeping process and practices.</p>

<p>10.3 Return of User's Data: Upon request by a User made within 30 (thirty) days after the effective date of termination of a   Services  , Testpan will make available to the User for download a copy of such User's data in comma separated value (csv) format or any other format as determined by Testpan. After such 30 (thirty) days period, Testpan shall have no obligation to maintain or provide any of such User's data and shall thereafter, unless legally prohibited, delete all User's data in its systems or otherwise in its possession or under its control. In cases where User terminates the   voluntarily, it will be the sole responsibility of the User to make a copy of their data before terminating the   Users data will not be available after termination of services in such cases.</p>

<p>10.4 This Agreement and any contractual obligation between Testpan and User will be governed by the laws of India, subject to the exclusive jurisdiction of Courts in Noida, India.</p>

<p>10.5 Even after termination, certain obligations mentioned under Covenants, Liability, Indemnity, Intellectual Property, Dispute Resolution will continue and survive termination.</p>

<p>10.6 Any amendment in these Terms shall replace all previous versions of the same.</p>

<p><strong>11. Theft of   services</strong></p>

<p>If the content of the user is stolen or it came to the knowledge of the user that his/her account with the   service is being misused or being used fraudulently, then the user agrees to notify Testpan immediately in writing or by mail to admin@testpanindia.com or by calling Testpan customer care on 011-28520481. User must provide the account details and detailed description of the circumstances of the theft or fraudulent use of the   services while calling or mailing Testpan. User will be liable for all use of the Services if his/her account is misused and also for any and all stolen services or fraudulent use of the service. Testpan shall not be liable to extend the service period or waive off any fees on account of such theft or fraudulent use. This includes, but is not limited to, modem hijacking, wireless hijacking, or other fraud arising out of a failure of your internal or corporate security procedures. </p>

<p><strong>12. Misuse of   services</strong></p>

<p>Testpan may restrict, suspend or terminate the account of any User who abuses or misuses the   Services. Misuse includes creating multiple or false profiles, infringing any intellectual property rights, violating any of the terms and conditions of these Terms of Use, or any other behavior that Testpan, in its sole discretion, deems contrary to its purpose. In addition, and without limiting the foregoing, Testpan has adopted a policy of terminating accounts of users who, in Testpan's sole discretion, are deemed to be repeat infringers of any Terms of Use even after being warned by Testpan.</p>

<p><strong>13. Severability and Waiver</strong></p>

<p>If any provision of this Terms of Use is held to be invalid or unenforceable, such provision shall be struck and the remaining provisions shall be enforced.</p>

<p><strong>14. Contact Information</strong></p>
<p>If a User has any question concerning Testpan, Services, the Service, this Agreement, please contact our customer support at the following email address: admin@testpanindia.com or via the contact information available from the following hyperlink: https://testpanindia.com/ .</p>

</span>



    <hr />
    
	<div style="clear:both;"></div>
      <div class="form-group col-12 col-lg-12">  
    <label style="font-size:15px; color:#333"></label> <br />
	<span style="color:#003"><a href="https://www.bookmytestcenter.com/" class="btn">Click here to Sign-in</a> </span>
	</div>
	
	
	</div>
	</div>	
	</div>		
<?php include('footer_new.php');?>
<script>
function isNumberKey(evt){
    var charCode = (evt.which) ? evt.which : event.keyCode
    if (charCode > 31 && (charCode < 48 || charCode > 57))
        return false;
    return true;
}
</script>
